# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09e801cfc89c02d13382c4e5000f2aa27c3ea04e6a0f537b3dec0a690735e48848ec7d0598244bb3278e600f627d68e601fc81c0f3a98e151255a12e8b18d7e1

test:
  secret_key_base: d7f8718d9854d606b7ccf6119c3acd5d7b781b3660698716da3c50cd124a874ecd2a238179bb5017f791d16cbadcd2071aa84ff0c9c2cc402d7c0f4505b0d669

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
